[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "jnose"
authors = [{name = "Luana", email = "martins.luana@ufba.br"}]
dynamic = ["version", "description"]
