# Configuração do Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email@email.com.br
spring.mail.password=senha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# JDBC / DataSource (HikariCP)
jdbc.driver=org.sqlite.JDBC
jdbc.url=jdbc:sqlite:jnose.db
jdbc.username=sa
jdbc.password=

# Hibernate
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
